// Instead of importing images from the public directory,
// export their public paths as strings

export const images = {
  primaryLogo: "/assets/images/primary-logo.png",
  buttonImage: "/assets/images/button-image.png",
  AssesmentImage: "/assets/images/Assessment_1_11zon.jpg",
  EndtoEndImage: "/assets/images/End-to-end_2_11zon.jpg",
  InteractiveImage: "/assets/images/Interactive-E-learning_4_11zon.jpg",
  TimelyDeliveryImage: "/assets/images/Timely-Delivery_6_11zon.jpg",
  InnovativeImage: "/assets/images/Innovative_3_11zon.jpg",
  VideoDevelopmentImage: "/assets/images/Video Development_7_11zon.jpg",
  ScalableImage: "/assets/images/Scalable-and-Cost-Effective_5_11zon.jpg",
  AtulImage: "/assets/images/atul_1_11zon.jpg",
  ShankarImage: "/assets/images/shankar_4_11zon.jpg",
  DilipImage: "/assets/images/dilip_2_11zon.jpg",
  PravinImage: "/assets/images/praveen_3_11zon.jpg",
  jyoti: "/assets/images/new-jyoti.png",
  prachi: "/assets/images/new-prachi.png",
  HerobackgroundImage: "/assets/images/hero-background.png",
  WhyChooseUsBgImage: "/assets/images/why-choosebg.png",
  OurServicesBgImage: "/assets/images/services-background.jpg",
  AIdrivector: "/assets/images/AIdrivenvector.png",
  Videovector: "/assets/images/Videodevector.png",
  EndtoVector: "/assets/images/endtoendvector.png",
  InteractiveVector: "/assets/images/interactivelearningvector.png",
  PostProVector: "/assets/images/postproductionvector.png",
  Bajaj: "/assets/images/Bajaj.png",
  Century: "/assets/images/Century.png",
  CSBbank: "/assets/images/csb.png",
  HDFCbank: "/assets/images/HDFC.png",
  Megamaart: "/assets/images/Mega.png",
  Tataclass: "/assets/images/tataclass.png",
  TataSteel: "/assets/images/tatasteel.png",
  aiservicesimage: "/assets/images/aiservices.jpg",
  consistentImage: "/assets/images/consistentquality.jpg",
  logo: "/assets/images/logo.png",
  TranslationServices : "/assets/images/translation-services.jpg",
  VoicoverImage : "/assets/images/Vover.jpg",
  FarhanNek: "/assets/images/farhan.png",	
  AniketBhasin: "/assets/images/aniket.png",
  NimishaKoli:	"/assets/images/nimisha.png",
  VrushaliSatpute: "/assets/images/vrushali.png",	
  Vedant: "/assets/images/vedant.png",
  HeroVideo: "/assets/images/hero-video.mp4",
  clientOne : "/assets/images/Letstute (Client logo)-01.jpg",
  clientTwo : "/assets/images/Letstute (Client logo)-02.jpg",
  clientThree : "/assets/images/Letstute (Client logo)-03.jpg",
  clientFour : "/assets/images/Letstute (Client logo)-04.jpg",
  clientFive : "/assets/images/Letstute (Client logo)-05.jpg",
  clientSix : "/assets/images/Letstute (Client logo)-06.jpg",
  clientSeven : "/assets/images/Letstute (Client logo)-07.jpg",
  clientEight : "/assets/images/Letstute (Client logo)-08.jpg",
  clientNine : "/assets/images/Letstute (Client logo)-09.jpg",
  clientTen : "/assets/images/Letstute (Client logo)-10.jpg",
  clientEleven : "/assets/images/Letstute (Client logo)-11.jpg",
  clientTwelve : "/assets/images/Letstute (Client logo)-12.jpg",

};
